# Toolchain for M33 bare‑metal (arm‑none‑eabi)
# Falls back to native compilers for testing if cross-compiler not available
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Skip CMake's compiler test for bare-metal (it will fail without startup/linker script)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Check if ARM_NONE_EABI_BIN is set and not empty, otherwise try system compiler, else use native
if(DEFINED ENV{ARM_NONE_EABI_BIN} AND NOT "$ENV{ARM_NONE_EABI_BIN}" STREQUAL "")
  set(TOOLCHAIN_BIN $ENV{ARM_NONE_EABI_BIN})
  set(CMAKE_C_COMPILER   ${TOOLCHAIN_BIN}/arm-none-eabi-gcc CACHE FILEPATH "" FORCE)
  set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BIN}/arm-none-eabi-g++ CACHE FILEPATH "" FORCE)
  set(CMAKE_ASM_COMPILER ${TOOLCHAIN_BIN}/arm-none-eabi-gcc CACHE FILEPATH "" FORCE)
  set(CMAKE_AR           ${TOOLCHAIN_BIN}/arm-none-eabi-ar  CACHE FILEPATH "" FORCE)
  set(CMAKE_RANLIB       ${TOOLCHAIN_BIN}/arm-none-eabi-ranlib CACHE FILEPATH "" FORCE)
  message(STATUS "Using ARM cross-compiler from: ${TOOLCHAIN_BIN}")
elseif(EXISTS /usr/bin/arm-none-eabi-gcc)
  set(CMAKE_C_COMPILER   /usr/bin/arm-none-eabi-gcc CACHE FILEPATH "" FORCE)
  set(CMAKE_CXX_COMPILER /usr/bin/arm-none-eabi-g++ CACHE FILEPATH "" FORCE)
  set(CMAKE_ASM_COMPILER /usr/bin/arm-none-eabi-gcc CACHE FILEPATH "" FORCE)
  set(CMAKE_AR           /usr/bin/arm-none-eabi-ar  CACHE FILEPATH "" FORCE)
  set(CMAKE_RANLIB       /usr/bin/arm-none-eabi-ranlib CACHE FILEPATH "" FORCE)
  message(STATUS "Using system ARM cross-compiler")
else()
  # Fallback to native for testing (won't run on actual hardware)
  message(WARNING "ARM cross-compiler not found. Using native compiler for build testing only!")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_HOST_SYSTEM_PROCESSOR})
  unset(CMAKE_C_COMPILER CACHE)
  unset(CMAKE_CXX_COMPILER CACHE)
  unset(CMAKE_ASM_COMPILER CACHE)
  unset(CMAKE_AR CACHE)
  unset(CMAKE_RANLIB CACHE)
endif()

# Cortex‑M33 flags (no OS for now)
set(COMMON_FLAGS "-mcpu=cortex-m33 -mthumb -O2 -ffunction-sections -fdata-sections")
set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}   ${COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMMON_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--gc-sections")
